-- EduManage — All module tables (academics, finance, HR, communication, LMS, library, medical, transport, boarding, AI)

-- ACADEMIC
create table if not exists public.academic_years (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, name text not null, start_date date not null, end_date date not null, is_active boolean default false, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.terms (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, academic_year_id uuid not null references public.academic_years(id) on delete cascade, name text not null, start_date date not null, end_date date not null, is_active boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.subjects (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, name text not null, code text, department text, is_compulsory boolean default true, metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists public.classes (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, name text not null, level text, academic_year_id uuid references public.academic_years(id) on delete set null, class_teacher_id uuid references public.user_profiles(id) on delete set null, capacity integer default 40, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.streams (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, class_id uuid not null references public.classes(id) on delete cascade, name text not null, stream_teacher_id uuid references public.user_profiles(id) on delete set null, capacity integer default 40, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.students (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, user_id uuid references public.user_profiles(id) on delete set null, admission_number text not null, full_name text not null, gender text, date_of_birth date, national_id text, birth_certificate text, class_id uuid references public.classes(id) on delete set null, stream_id uuid references public.streams(id) on delete set null, enrollment_date date default current_date, status text default 'active', graduation_date date, transfer_date date, previous_school text, address text, county text, nationality text, blood_group text, photo_url text, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(school_id, admission_number));
create table if not exists public.guardians (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, user_id uuid references public.user_profiles(id) on delete set null, student_id uuid not null references public.students(id) on delete cascade, full_name text not null, relationship text, phone text, email text, occupation text, is_primary boolean default false, is_emergency_contact boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.teachers (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, user_id uuid references public.user_profiles(id) on delete set null, employee_number text not null, full_name text not null, gender text, date_of_birth date, national_id text, tsc_number text, department text, qualification text, specialization text, employment_date date default current_date, contract_type text, status text default 'active', termination_date date, phone text, email text, address text, photo_url text, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(school_id, employee_number));
create table if not exists public.teacher_subjects (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, teacher_id uuid not null references public.teachers(id) on delete cascade, subject_id uuid not null references public.subjects(id) on delete cascade, class_id uuid references public.classes(id) on delete cascade, stream_id uuid references public.streams(id) on delete cascade, is_main_teacher boolean default false, created_at timestamptz default now(), unique(teacher_id, subject_id, class_id, stream_id));
create table if not exists public.timetable_slots (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, class_id uuid not null references public.classes(id) on delete cascade, stream_id uuid references public.streams(id) on delete cascade, subject_id uuid references public.subjects(id) on delete set null, teacher_id uuid references public.teachers(id) on delete set null, day_of_week smallint not null, start_time time not null, end_time time not null, room text, term_id uuid references public.terms(id) on delete cascade, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.attendance (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, class_id uuid references public.classes(id) on delete set null, date date not null, status text not null, arrival_time time, remarks text, marked_by uuid references public.user_profiles(id) on delete set null, created_at timestamptz default now(), updated_at timestamptz default now(), unique(school_id, student_id, date));
create table if not exists public.exams (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, name text not null, term_id uuid references public.terms(id) on delete set null, exam_type text, start_date date, end_date date, max_score integer default 100, weight numeric(5,2) default 100.00, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.exam_results (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, exam_id uuid not null references public.exams(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, subject_id uuid not null references public.subjects(id) on delete cascade, class_id uuid references public.classes(id) on delete set null, score numeric(6,2) not null, grade text, remarks text, recorded_by uuid references public.user_profiles(id) on delete set null, created_at timestamptz default now(), updated_at timestamptz default now(), unique(exam_id, student_id, subject_id));
create table if not exists public.report_cards (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, class_id uuid references public.classes(id) on delete set null, stream_id uuid references public.streams(id) on delete set null, term_id uuid not null references public.terms(id) on delete cascade, total_score numeric(8,2), average_score numeric(6,2), grade text, position integer, stream_position integer, conduct text, teacher_remarks text, principal_remarks text, generated_at timestamptz default now(), pdf_url text, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(student_id, term_id));
create table if not exists public.assignments (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, title text not null, description text, subject_id uuid references public.subjects(id) on delete set null, class_id uuid references public.classes(id) on delete cascade, stream_id uuid references public.streams(id) on delete set null, teacher_id uuid references public.teachers(id) on delete set null, term_id uuid references public.terms(id) on delete set null, assigned_at timestamptz default now(), due_at timestamptz, max_score integer default 100, attachment_url text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.assignment_submissions (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, assignment_id uuid not null references public.assignments(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, submitted_at timestamptz default now(), submission_url text, submission_text text, score numeric(6,2), graded_by uuid references public.user_profiles(id) on delete set null, graded_at timestamptz, feedback text, ai_feedback text, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(assignment_id, student_id));
create table if not exists public.lessons (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, title text not null, description text, subject_id uuid references public.subjects(id) on delete set null, class_id uuid references public.classes(id) on delete cascade, teacher_id uuid references public.teachers(id) on delete set null, content_url text, notes text, scheduled_at timestamptz, duration_minutes integer default 40, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.quizzes (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, title text not null, description text, subject_id uuid references public.subjects(id) on delete set null, class_id uuid references public.classes(id) on delete cascade, teacher_id uuid references public.teachers(id) on delete set null, total_marks integer default 100, pass_mark integer default 50, duration_minutes integer default 60, start_at timestamptz, end_at timestamptz, is_auto_marked boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.quiz_questions (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, quiz_id uuid not null references public.quizzes(id) on delete cascade, question_text text not null, question_type text, options jsonb, correct_answer text, marks integer default 1, explanation text, position integer default 0, created_at timestamptz default now());
create table if not exists public.quiz_attempts (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, quiz_id uuid not null references public.quizzes(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, answers jsonb, score numeric(6,2), total_marks integer, started_at timestamptz default now(), submitted_at timestamptz, passed boolean, created_at timestamptz default now());
create table if not exists public.learning_resources (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, title text not null, description text, resource_type text, url text, subject_id uuid references public.subjects(id) on delete set null, class_id uuid references public.classes(id) on delete set null, uploaded_by uuid references public.user_profiles(id) on delete set null, is_public boolean default false, metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists public.student_progress (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, subject_id uuid references public.subjects(id) on delete set null, metric text, value numeric(10,2), recorded_at timestamptz default now(), metadata jsonb default '{}'::jsonb);

-- FINANCE
create table if not exists public.fee_structures (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, name text not null, class_id uuid references public.classes(id) on delete set null, stream_id uuid references public.streams(id) on delete set null, term_id uuid references public.terms(id) on delete set null, academic_year_id uuid references public.academic_years(id) on delete set null, tuition_fee numeric(12,2) default 0, boarding_fee numeric(12,2) default 0, transport_fee numeric(12,2) default 0, library_fee numeric(12,2) default 0, medical_fee numeric(12,2) default 0, activity_fee numeric(12,2) default 0, other_fee numeric(12,2) default 0, total numeric(12,2) generated always as (tuition_fee + boarding_fee + transport_fee + library_fee + medical_fee + activity_fee + other_fee) stored, currency text default 'KES', metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.invoices (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, invoice_number text not null, student_id uuid not null references public.students(id) on delete cascade, fee_structure_id uuid references public.fee_structures(id) on delete set null, term_id uuid references public.terms(id) on delete set null, amount_due numeric(12,2) not null, amount_paid numeric(12,2) default 0, balance numeric(12,2) generated always as (amount_due - amount_paid) stored, issue_date date default current_date, due_date date, status text default 'unpaid', currency text default 'KES', metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(school_id, invoice_number));
create table if not exists public.payments (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, payment_number text not null, invoice_id uuid references public.invoices(id) on delete set null, student_id uuid not null references public.students(id) on delete cascade, amount numeric(12,2) not null, payment_method text not null, payment_provider_ref text, paid_by uuid references public.user_profiles(id) on delete set null, paid_by_name text, received_by uuid references public.user_profiles(id) on delete set null, paid_at timestamptz default now(), currency text default 'KES', status text default 'completed', remarks text, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(school_id, payment_number));
create table if not exists public.receipts (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, receipt_number text not null, payment_id uuid not null references public.payments(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, amount numeric(12,2) not null, pdf_url text, issued_at timestamptz default now(), issued_by uuid references public.user_profiles(id) on delete set null, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), unique(school_id, receipt_number));
create table if not exists public.scholarships (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, name text not null, student_id uuid references public.students(id) on delete cascade, amount numeric(12,2), percentage numeric(5,2), reason text, awarded_at date default current_date, expires_at date, awarded_by uuid references public.user_profiles(id) on delete set null, metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists public.fines (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, reason text not null, amount numeric(12,2) not null, issued_at timestamptz default now(), paid boolean default false, paid_at timestamptz, issued_by uuid references public.user_profiles(id) on delete set null, metadata jsonb default '{}'::jsonb);
create table if not exists public.payment_provider_config (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, provider text not null, config jsonb not null, is_active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now(), unique(school_id, provider));
create table if not exists public.financial_reports (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, report_type text not null, period_start date not null, period_end date not null, total_billed numeric(14,2), total_collected numeric(14,2), total_outstanding numeric(14,2), total_scholarships numeric(14,2), total_fines numeric(14,2), summary jsonb default '{}'::jsonb, generated_at timestamptz default now(), metadata jsonb default '{}'::jsonb);

-- HR
create table if not exists public.staff_records (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, user_id uuid references public.user_profiles(id) on delete set null, employee_number text not null, full_name text not null, gender text, date_of_birth date, national_id text, department text, position text, role user_role, employment_date date default current_date, contract_type text, contract_end_date date, basic_salary numeric(12,2) default 0, allowances numeric(12,2) default 0, deductions numeric(12,2) default 0, status text default 'active', termination_date date, phone text, email text, address text, photo_url text, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(school_id, employee_number));
create table if not exists public.payroll_runs (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, period_month integer not null, period_year integer not null, total_gross numeric(14,2) default 0, total_deductions numeric(14,2) default 0, total_net numeric(14,2) default 0, status text default 'draft', processed_at timestamptz, approved_by uuid references public.user_profiles(id) on delete set null, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(school_id, period_month, period_year));
create table if not exists public.payroll_items (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, payroll_run_id uuid not null references public.payroll_runs(id) on delete cascade, staff_record_id uuid references public.staff_records(id) on delete set null, teacher_id uuid references public.teachers(id) on delete set null, employee_name text, basic_salary numeric(12,2) default 0, allowances numeric(12,2) default 0, overtime numeric(12,2) default 0, tax_paye numeric(12,2) default 0, nssf numeric(12,2) default 0, nhif numeric(12,2) default 0, other_deductions numeric(12,2) default 0, gross_pay numeric(12,2) generated always as (basic_salary + allowances + overtime) stored, total_deductions numeric(12,2) generated always as (tax_paye + nssf + nhif + other_deductions) stored, net_pay numeric(12,2) generated always as (basic_salary + allowances + overtime - tax_paye - nssf - nhif - other_deductions) stored, paid_at timestamptz, payment_ref text, metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists public.leave_requests (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, staff_record_id uuid references public.staff_records(id) on delete set null, teacher_id uuid references public.teachers(id) on delete set null, leave_type text not null, start_date date not null, end_date date not null, days numeric(5,1), reason text, status text default 'pending', approved_by uuid references public.user_profiles(id) on delete set null, approved_at timestamptz, attachment_url text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.performance_reviews (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, staff_record_id uuid references public.staff_records(id) on delete set null, teacher_id uuid references public.teachers(id) on delete set null, review_period text, reviewer_id uuid references public.user_profiles(id) on delete set null, score numeric(4,2), strengths text, areas_for_improvement text, goals text, comments text, reviewed_at timestamptz default now(), metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists public.disciplinary_records (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, staff_record_id uuid references public.staff_records(id) on delete set null, teacher_id uuid references public.teachers(id) on delete set null, student_id uuid references public.students(id) on delete set null, incident_date date not null, incident_description text not null, severity text, action_taken text, recorded_by uuid references public.user_profiles(id) on delete set null, attachment_url text, status text default 'open', metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists public.recruitment_applications (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, position text not null, applicant_name text not null, applicant_email text not null, applicant_phone text, cv_url text, cover_letter text, status text default 'received', interview_date timestamptz, notes text, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());

-- COMMUNICATION
create table if not exists public.announcements (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, title text not null, body text not null, category text, audience text, class_id uuid references public.classes(id) on delete set null, created_by uuid references public.user_profiles(id) on delete set null, is_pinned boolean default false, published_at timestamptz default now(), expires_at timestamptz, attachment_url text, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.message_groups (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, name text, group_type text, created_by uuid references public.user_profiles(id) on delete set null, created_at timestamptz default now());
create table if not exists public.message_group_members (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, group_id uuid not null references public.message_groups(id) on delete cascade, user_id uuid not null references public.user_profiles(id) on delete cascade, joined_at timestamptz default now(), unique(group_id, user_id));
create table if not exists public.messages (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, sender_id uuid not null references public.user_profiles(id) on delete cascade, recipient_id uuid references public.user_profiles(id) on delete cascade, group_id uuid references public.message_groups(id) on delete cascade, body text, attachment_url text, message_type text default 'text', read_at timestamptz, created_at timestamptz default now());
create table if not exists public.sms_logs (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, recipient_phone text not null, recipient_name text, message text not null, status text default 'queued', provider text, provider_ref text, sent_by uuid references public.user_profiles(id) on delete set null, sent_at timestamptz default now(), delivered_at timestamptz, metadata jsonb default '{}'::jsonb);
create table if not exists public.email_logs (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, recipient_email text not null, recipient_name text, subject text not null, body text, status text default 'queued', provider text, provider_ref text, sent_by uuid references public.user_profiles(id) on delete set null, sent_at timestamptz default now(), delivered_at timestamptz, metadata jsonb default '{}'::jsonb);
create table if not exists public.events (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, title text not null, description text, event_type text, start_at timestamptz not null, end_at timestamptz, location text, audience text, class_id uuid references public.classes(id) on delete set null, created_by uuid references public.user_profiles(id) on delete set null, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.visitors (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, visitor_name text not null, visitor_phone text, visitor_id_number text, purpose text, host_name text, host_id uuid references public.user_profiles(id) on delete set null, check_in_at timestamptz default now(), check_out_at timestamptz, vehicle_plate text, metadata jsonb default '{}'::jsonb, created_at timestamptz default now());

-- LIBRARY
create table if not exists public.library_books (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, isbn text, title text not null, author text, publisher text, publication_year integer, category text, subject_id uuid references public.subjects(id) on delete set null, edition text, barcode text, total_copies integer default 1, available_copies integer default 1, shelf_location text, description text, cover_url text, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.library_borrows (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, book_id uuid not null references public.library_books(id) on delete cascade, borrower_user_id uuid references public.user_profiles(id) on delete set null, student_id uuid references public.students(id) on delete set null, staff_id uuid references public.staff_records(id) on delete set null, teacher_id uuid references public.teachers(id) on delete set null, borrowed_at timestamptz default now(), due_at timestamptz not null, returned_at timestamptz, returned_to uuid references public.user_profiles(id) on delete set null, fine_amount numeric(10,2) default 0, fine_paid boolean default false, status text default 'borrowed', remarks text, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());

-- MEDICAL
create table if not exists public.medical_records (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, blood_group text, height numeric(5,2), weight numeric(5,2), allergies jsonb default '[]'::jsonb, chronic_conditions jsonb default '[]'::jsonb, medications jsonb default '[]'::jsonb, immunizations jsonb default '[]'::jsonb, doctor_name text, doctor_phone text, hospital text, emergency_contact_name text, emergency_contact_phone text, emergency_contact_relationship text, notes text, created_at timestamptz default now(), updated_at timestamptz default now(), unique(school_id, student_id));
create table if not exists public.medical_visits (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, visit_date timestamptz default now(), chief_complaint text, diagnosis text, treatment_given text, medication_administered text, temperature numeric(4,1), blood_pressure text, pulse integer, notes text, attended_by uuid references public.user_profiles(id) on delete set null, sent_home boolean default false, referred_to_hospital boolean default false, parent_notified boolean default false, metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists public.medication_administrations (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, medication_name text not null, dosage text, administered_at timestamptz default now(), administered_by uuid references public.user_profiles(id) on delete set null, reason text, notes text, metadata jsonb default '{}'::jsonb, created_at timestamptz default now());

-- TRANSPORT
create table if not exists public.transport_routes (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, route_name text not null, route_code text, start_point text, end_point text, distance_km numeric(8,2), pickup_time time, drop_time time, fee numeric(10,2) default 0, is_active boolean default true, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.transport_vehicles (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, registration_number text not null, vehicle_type text, make text, model text, year integer, capacity integer, color text, insurance_provider text, insurance_expiry date, road_worthiness_expiry date, assigned_route_id uuid references public.transport_routes(id) on delete set null, driver_id uuid references public.staff_records(id) on delete set null, is_active boolean default true, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(school_id, registration_number));
create table if not exists public.transport_drivers (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, staff_id uuid references public.staff_records(id) on delete set null, full_name text not null, license_number text, license_expiry date, phone text, assigned_vehicle_id uuid references public.transport_vehicles(id) on delete set null, assigned_route_id uuid references public.transport_routes(id) on delete set null, is_active boolean default true, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.transport_assignments (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, route_id uuid not null references public.transport_routes(id) on delete cascade, vehicle_id uuid references public.transport_vehicles(id) on delete set null, pickup_point text, drop_point text, term_id uuid references public.terms(id) on delete set null, is_active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.transport_logs (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, vehicle_id uuid not null references public.transport_vehicles(id) on delete cascade, route_id uuid references public.transport_routes(id) on delete set null, driver_id uuid references public.transport_drivers(id) on delete set null, log_type text, log_date date default current_date, amount numeric(10,2), odometer_reading integer, description text, attachment_url text, recorded_by uuid references public.user_profiles(id) on delete set null, metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists public.transport_fees (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, route_name text not null, route_id uuid references public.transport_routes(id) on delete set null, amount numeric(12,2) not null, currency text default 'KES', term_id uuid references public.terms(id) on delete set null, created_at timestamptz default now());

-- BOARDING
create table if not exists public.dormitories (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, name text not null, gender text, capacity integer default 40, house_master_id uuid references public.staff_records(id) on delete set null, location text, is_active boolean default true, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.dormitory_beds (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, dormitory_id uuid not null references public.dormitories(id) on delete cascade, bed_number text not null, room_number text, is_occupied boolean default false, assigned_student_id uuid references public.students(id) on delete set null, assigned_at timestamptz, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(dormitory_id, bed_number));
create table if not exists public.boarding_attendance (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, dormitory_id uuid not null references public.dormitories(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, date date not null, status text not null, check_in_time time, check_out_time time, remarks text, marked_by uuid references public.user_profiles(id) on delete set null, created_at timestamptz default now(), unique(school_id, student_id, date));
create table if not exists public.dormitory_inspections (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, dormitory_id uuid not null references public.dormitories(id) on delete cascade, inspection_date date default current_date, inspected_by uuid references public.user_profiles(id) on delete set null, cleanliness_score integer, discipline_score integer, notes text, follow_up_required boolean default false, metadata jsonb default '{}'::jsonb, created_at timestamptz default now());

-- AI
create table if not exists public.ai_usage_logs (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, user_id uuid not null references public.user_profiles(id) on delete cascade, feature text not null, provider text, model text, tokens_used integer default 0, cost_usd numeric(10,6) default 0, metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists public.ai_provider_config (id uuid primary key default gen_random_uuid(), school_id uuid references public.schools(id) on delete cascade, provider text not null, api_key_encrypted text, default_model text, is_active boolean default true, max_tokens_per_request integer default 2048, temperature numeric(3,2) default 0.70, metadata jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(school_id, provider));
create table if not exists public.ai_conversations (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, user_id uuid not null references public.user_profiles(id) on delete cascade, feature text not null, title text, messages jsonb default '[]'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());

-- RLS + policies (macro pattern)
do $$ declare t text; tables text[] := array[
  'academic_years','terms','subjects','classes','streams','students','guardians','teachers','teacher_subjects','timetable_slots','attendance','exams','exam_results','report_cards','assignments','assignment_submissions','lessons','quizzes','quiz_questions','quiz_attempts','learning_resources','student_progress',
  'fee_structures','invoices','payments','receipts','scholarships','fines','transport_fees','payment_provider_config','financial_reports',
  'staff_records','payroll_runs','payroll_items','leave_requests','performance_reviews','disciplinary_records','recruitment_applications',
  'announcements','messages','message_groups','message_group_members','sms_logs','email_logs','events','visitors',
  'library_books','library_borrows','medical_records','medical_visits','medication_administrations',
  'transport_routes','transport_vehicles','transport_drivers','transport_assignments','transport_logs',
  'dormitories','dormitory_beds','boarding_attendance','dormitory_inspections',
  'ai_usage_logs','ai_provider_config','ai_conversations'
];
begin foreach t in array tables loop
  execute format('alter table public.%I enable row level security', t);
  execute format('drop policy if exists %1$s_select on public.%1$s', t);
  execute format('create policy %1$s_select on public.%1$I for select using (public.is_platform_admin() or public.is_school_staff(school_id))', t);
  execute format('drop policy if exists %1$s_insert on public.%1$s', t);
  execute format('create policy %1$s_insert on public.%1$I for insert with check (public.is_platform_admin() or public.is_school_admin(school_id))', t);
  execute format('drop policy if exists %1$s_update on public.%1$s', t);
  execute format('create policy %1$s_update on public.%1$I for update using (public.is_platform_admin() or public.is_school_admin(school_id))', t);
  execute format('drop policy if exists %1$s_delete on public.%1$s', t);
  execute format('create policy %1$s_delete on public.%1$I for delete using (public.is_platform_admin() or public.is_school_admin(school_id))', t);
end loop; end $$;

-- Self-access for students
drop policy if exists students_self_select on public.students;
create policy students_self_select on public.students for select using (user_id = public.current_profile_id());
drop policy if exists attendance_self_select on public.attendance;
create policy attendance_self_select on public.attendance for select using (exists (select 1 from public.students s where s.id = attendance.student_id and s.user_id = public.current_profile_id()));
drop policy if exists exam_results_self_select on public.exam_results;
create policy exam_results_self_select on public.exam_results for select using (exists (select 1 from public.students s where s.id = exam_results.student_id and s.user_id = public.current_profile_id()));
drop policy if exists report_cards_self_select on public.report_cards;
create policy report_cards_self_select on public.report_cards for select using (exists (select 1 from public.students s where s.id = report_cards.student_id and s.user_id = public.current_profile_id()));
drop policy if exists assignments_class_select on public.assignments;
create policy assignments_class_select on public.assignments for select using (public.is_platform_admin() or public.is_school_staff(school_id) or exists (select 1 from public.students s where s.user_id = public.current_profile_id() and s.class_id = assignments.class_id));
drop policy if exists assignment_submissions_student_insert on public.assignment_submissions;
create policy assignment_submissions_student_insert on public.assignment_submissions for insert with check (exists (select 1 from public.students s where s.id = assignment_submissions.student_id and s.user_id = public.current_profile_id()));
drop policy if exists quiz_attempts_student_insert on public.quiz_attempts;
create policy quiz_attempts_student_insert on public.quiz_attempts for insert with check (exists (select 1 from public.students s where s.id = quiz_attempts.student_id and s.user_id = public.current_profile_id()));
drop policy if exists students_parent_select on public.students;
create policy students_parent_select on public.students for select using (exists (select 1 from public.guardians g where g.student_id = students.id and g.user_id = public.current_profile_id()));
drop policy if exists messages_self_select on public.messages;
create policy messages_self_select on public.messages for select using (sender_id = public.current_profile_id() or recipient_id = public.current_profile_id() or exists (select 1 from public.message_group_members mgm where mgm.group_id = messages.group_id and mgm.user_id = public.current_profile_id()));
drop policy if exists messages_self_insert on public.messages;
create policy messages_self_insert on public.messages for insert with check (sender_id = public.current_profile_id());

-- DB-level school_id enforcement
create or replace function public.enforce_school_id() returns trigger language plpgsql as $$
begin if new.school_id is null then raise exception 'school_id is required on table %', TG_TABLE_NAME; end if; return new; end $$;
do $$ declare t text; tables text[] := array[
  'academic_years','terms','subjects','classes','streams','students','guardians','teachers','teacher_subjects','timetable_slots','attendance','exams','exam_results','report_cards','assignments','assignment_submissions','lessons','quizzes','quiz_questions','quiz_attempts','learning_resources','student_progress',
  'fee_structures','invoices','payments','receipts','scholarships','fines','transport_fees','payment_provider_config','financial_reports',
  'staff_records','payroll_runs','payroll_items','leave_requests','performance_reviews','disciplinary_records','recruitment_applications',
  'announcements','messages','message_groups','message_group_members','sms_logs','email_logs','events','visitors',
  'library_books','library_borrows','medical_records','medical_visits','medication_administrations',
  'transport_routes','transport_vehicles','transport_drivers','transport_assignments','transport_logs',
  'dormitories','dormitory_beds','boarding_attendance','dormitory_inspections','ai_usage_logs','ai_conversations'
];
begin foreach t in array tables loop
  execute format('drop trigger if exists trg_%1$s_enforce_school on public.%1$I', t);
  execute format('create trigger trg_%1$s_enforce_school before insert on public.%1$I for each row execute function public.enforce_school_id()', t);
  execute format('drop trigger if exists trg_%1$s_touch on public.%1$I', t);
  execute format('create trigger trg_%1$s_touch before update on public.%1$I for each row execute function public.touch_updated_at()', t);
end loop; end $$;

-- Atomic AI usage limit RPC
create or replace function public.check_and_increment_ai_usage(p_school_id uuid) returns boolean language plpgsql security definer as $$
declare v_count integer; v_limit integer;
begin select ai_usage_count, ai_usage_limit into v_count, v_limit from public.schools where id = p_school_id for update;
if not found then return false; end if;
if v_count >= v_limit then return false; end if;
update public.schools set ai_usage_count = ai_usage_count + 1 where id = p_school_id;
return true; end $$;
create or replace function public.check_student_limit(p_school_id uuid) returns boolean language plpgsql security definer as $$
declare v_count integer; v_limit integer;
begin select count(*), s.max_students into v_count, v_limit from public.students st join public.schools s on s.id = st.school_id where st.school_id = p_school_id and st.status = 'active' group by s.max_students;
if not found then select max_students into v_limit from public.schools where id = p_school_id; return v_limit is null or 0 < v_limit; end if;
return v_count < v_limit; end $$;
